"use client";
import Link from "next/link";
import { useCart } from "@/context/cart-context";
import { formatFcfa } from "@/lib/format";
import { STORE_CONFIG } from "@/lib/store-config";

export default function CartPage() {
  const { items, subtotal, fulfillmentFee, total, fulfillmentMethod, setFulfillmentMethod, setItemQuantity } = useCart();
  if (!items.length) return <section className="pt-3"><h1 className="text-3xl font-bold tracking-tight">Votre panier</h1><p className="mt-3 text-sm text-neutral-600 dark:text-neutral-400">Votre panier est vide.</p><Link href="/rayons" className="mt-6 inline-flex rounded-xl bg-black px-4 py-3 text-sm font-semibold text-white dark:bg-white dark:text-black">Explorer les rayons</Link></section>;
  return <section className="pt-3"><h1 className="text-3xl font-bold tracking-tight">Votre panier</h1><div className="mt-5 space-y-3">{items.map((item) => <article key={item.id} className="flex items-center justify-between rounded-2xl border border-[#E5E5E5] p-3 dark:border-[#262626]"><div><p className="text-xs font-bold uppercase text-neutral-500">{item.brand}</p><p className="mt-1 text-sm font-semibold">{item.title}</p><p className="mt-1 font-mono text-sm font-bold tabular-nums">{formatFcfa(item.price)}</p></div><div className="flex items-center gap-3"><button onClick={() => setItemQuantity(item.id, item.quantity - 1)} className="grid size-9 place-items-center rounded-lg bg-[#F5F5F7] dark:bg-[#141414]" aria-label="Retirer une unité">−</button><span className="w-4 text-center font-mono tabular-nums">{item.quantity}</span><button onClick={() => setItemQuantity(item.id, item.quantity + 1)} className="grid size-9 place-items-center rounded-lg bg-black text-white dark:bg-white dark:text-black" aria-label="Ajouter une unité">+</button></div></article>)}</div><fieldset className="mt-6 space-y-2"><legend className="mb-2 text-sm font-bold">Mode de réception</legend><label className="flex items-center justify-between rounded-xl border border-[#E5E5E5] p-3 dark:border-[#262626]"><span><b className="block text-sm">Livraison</b><small className="text-neutral-500">{STORE_CONFIG.delivery.estimatedTime} · {formatFcfa(STORE_CONFIG.delivery.fee)}</small></span><input type="radio" checked={fulfillmentMethod === "delivery"} onChange={() => setFulfillmentMethod("delivery")} /></label><label className="flex items-center justify-between rounded-xl border border-[#E5E5E5] p-3 dark:border-[#262626]"><span><b className="block text-sm">Retrait gratuit</b><small className="text-neutral-500">{STORE_CONFIG.pickup.location}</small></span><input type="radio" checked={fulfillmentMethod === "pickup"} onChange={() => setFulfillmentMethod("pickup")} /></label></fieldset><div className="mt-6 rounded-2xl bg-black p-4 text-white dark:bg-white dark:text-black"><div className="flex justify-between text-sm"><span>Sous-total</span><span className="font-mono tabular-nums">{formatFcfa(subtotal)}</span></div><div className="mt-2 flex justify-between text-sm"><span>Réception</span><span className="font-mono tabular-nums">{formatFcfa(fulfillmentFee)}</span></div><div className="mt-4 flex justify-between border-t border-white/25 pt-4 font-bold dark:border-black/25"><span>Total</span><span className="font-mono tabular-nums">{formatFcfa(total)}</span></div></div><Link href="/checkout" className="mt-4 block w-full rounded-xl bg-black py-4 text-center text-sm font-bold text-white dark:bg-white dark:text-black">Passer la commande</Link></section>;
}
