"use client";
/* eslint-disable @next/next/no-img-element -- Catalogue image origins are configured with the media service in the next phase. */
import { useCart, type CartProduct } from "@/context/cart-context";
import { formatFcfa } from "@/lib/format";
import Link from "next/link";
import { useState } from "react";
import { m, useReducedMotion } from "motion/react";
export type ProductCardProps = CartProduct & { stock: number; previousPrice?: number; imageUrl?: string; slug?: string; defaultVariantId?: string; defaultVariantValue?: string; defaultVariantPrice?: number };
export function ProductCard({ stock, previousPrice, imageUrl, defaultVariantId, defaultVariantValue, defaultVariantPrice, ...product }: ProductCardProps) {
  const { addItem } = useCart(); const isLowStock = stock > 0 && stock <= 5;
  const [justAdded, setJustAdded] = useState(false); const reducedMotion = useReducedMotion();
  function addToCart() { addItem({ ...product, id: defaultVariantId ?? product.id, title: defaultVariantValue ? `${product.title} — ${defaultVariantValue}` : product.title, price: defaultVariantPrice ?? product.price }); setJustAdded(true); window.setTimeout(() => setJustAdded(false), 1200); }
  return <article className="group overflow-hidden rounded-2xl border border-[#E5E5E5] bg-white dark:border-[#262626] dark:bg-[#141414]"><div className="relative aspect-square overflow-hidden bg-[#F5F5F7] dark:bg-[#0A0A0A]">{imageUrl ? <img src={imageUrl} alt={product.title} className="size-full object-cover transition-opacity duration-300" /> : <div className="flex size-full flex-col items-center justify-center text-center"><span className="text-4xl font-black tracking-[-0.12em] text-black/10 dark:text-white/10">{product.imageLabel}</span><span className="mt-2 text-[9px] font-bold uppercase tracking-[0.2em] text-black/35 dark:text-white/35">Visuel produit</span></div>}<span className="absolute left-2 top-2 rounded-full bg-black px-2 py-1 text-[9px] font-bold uppercase tracking-wide text-white dark:bg-white dark:text-black">{stock === 0 ? "Épuisé" : isLowStock ? `Plus que ${stock}` : "En stock"}</span></div><div className="p-3"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-neutral-500 dark:text-neutral-400">{product.brand}</p><h2 className="mt-1 min-h-10 text-sm font-semibold leading-5 text-black dark:text-white">{product.slug ? <Link href={`/produits/${product.slug}`}>{product.title}</Link> : product.title}</h2><div className="mt-3 flex items-end justify-between gap-2"><div><p className="font-mono text-sm font-bold tabular-nums text-black dark:text-white">{formatFcfa(defaultVariantPrice ?? product.price)}</p>{previousPrice ? <p className="font-mono text-[10px] tabular-nums text-neutral-500 line-through">{formatFcfa(previousPrice)}</p> : null}</div><m.button type="button" whileTap={reducedMotion ? undefined : { scale: 0.9 }} onClick={addToCart} disabled={stock === 0 || !defaultVariantId} className="grid size-10 shrink-0 place-items-center rounded-xl bg-black text-xl font-light text-white disabled:cursor-not-allowed disabled:bg-neutral-300 dark:bg-white dark:text-black dark:disabled:bg-neutral-700" aria-label={`Ajouter ${product.title} au panier`}>{justAdded ? "✓" : "+"}</m.button></div><span className="sr-only" aria-live="polite">{justAdded ? `${product.title} ajouté au panier` : ""}</span></div></article>;
}
